"""Candidate book titles and authors for Open Library import."""

CANDIDATES = [
    # Continuing authors from original 20:
    ("Harry Potter and the Chamber of Secrets", "J.K. Rowling"),
    ("Harry Potter and the Prisoner of Azkaban", "J.K. Rowling"),
    ("Harry Potter and the Goblet of Fire", "J.K. Rowling"),
    ("Harry Potter and the Order of the Phoenix", "J.K. Rowling"),
    ("Harry Potter and the Half-Blood Prince", "J.K. Rowling"),
    ("Harry Potter and the Deathly Hallows", "J.K. Rowling"),
    ("The Silmarillion", "J.R.R. Tolkien"),
    ("The Fellowship of the Ring", "J.R.R. Tolkien"),
    ("The Two Towers", "J.R.R. Tolkien"),
    ("The Return of the King", "J.R.R. Tolkien"),
    ("The Lion, the Witch and the Wardrobe", "C.S. Lewis"),
    ("Prince Caspian", "C.S. Lewis"),
    ("The Voyage of the Dawn Treader", "C.S. Lewis"),
    ("The Magician's Nephew", "C.S. Lewis"),
    ("The Sea of Monsters", "Rick Riordan"),
    ("The Titan's Curse", "Rick Riordan"),
    ("The Battle of the Labyrinth", "Rick Riordan"),
    ("The Last Olympian", "Rick Riordan"),
    ("Catching Fire", "Suzanne Collins"),
    ("Mockingjay", "Suzanne Collins"),
    ("The Ballad of Songbirds and Snakes", "Suzanne Collins"),
    ("The Scorch Trials", "James Dashner"),
    ("The Death Cure", "James Dashner"),
    ("The Kill Order", "James Dashner"),
    ("Dune Messiah", "Frank Herbert"),
    ("Children of Dune", "Frank Herbert"),
    ("God Emperor of Dune", "Frank Herbert"),
    ("Animal Farm", "George Orwell"),
    ("Homage to Catalonia", "George Orwell"),
    ("Project Hail Mary", "Andy Weir"),
    ("Artemis", "Andy Weir"),
    ("A Study in Scarlet", "Arthur Conan Doyle"),
    ("The Sign of the Four", "Arthur Conan Doyle"),
    ("The Hound of the Baskervilles", "Arthur Conan Doyle"),
    ("The Valley of Fear", "Arthur Conan Doyle"),
    ("Angels & Demons", "Dan Brown"),
    ("The Lost Symbol", "Dan Brown"),
    ("Inferno", "Dan Brown"),
    ("Sense and Sensibility", "Jane Austen"),
    ("Emma", "Jane Austen"),
    ("Mansfield Park", "Jane Austen"),
    ("Persuasion", "Jane Austen"),
    ("Northanger Abbey", "Jane Austen"),
    ("Villette", "Charlotte Bronte"),
    ("Shirley", "Charlotte Bronte"),
    ("Little Men", "Louisa May Alcott"),
    ("Jo's Boys", "Louisa May Alcott"),
    ("Veronika Decides to Die", "Paulo Coelho"),
    ("Eleven Minutes", "Paulo Coelho"),
    ("I Am the Messenger", "Markus Zusak"),
    ("Bridge of Clay", "Markus Zusak"),
    ("This Side of Paradise", "F. Scott Fitzgerald"),
    ("Tender Is the Night", "F. Scott Fitzgerald"),
    ("Go Set a Watchman", "Harper Lee"),
    ("Looking for Alaska", "John Green"),
    ("Paper Towns", "John Green"),
    ("An Abundance of Katherines", "John Green"),
    ("Turtles All the Way Down", "John Green"),
]
