// Sample graph data will be added here.


MERGE (jk:Author {name: 'J.K. Rowling'})
MERGE (tolkien:Author {name: 'J.R.R. Tolkien'})
MERGE (lewis:Author {name: 'C.S. Lewis'})
MERGE (riordan:Author {name: 'Rick Riordan'})
MERGE (collins:Author {name: 'Suzanne Collins'})
MERGE (dashner:Author {name: 'James Dashner'})
MERGE (herbert:Author {name: 'Frank Herbert'})
MERGE (orwell:Author {name: 'George Orwell'})
MERGE (weir:Author {name: 'Andy Weir'})
MERGE (doyle:Author {name: 'Arthur Conan Doyle'})
MERGE (brown:Author {name: 'Dan Brown'})
MERGE (austen:Author {name: 'Jane Austen'})
MERGE (bronte:Author {name: 'Charlotte Bronte'})
MERGE (alcott:Author {name: 'Louisa May Alcott'})
MERGE (coelho:Author {name: 'Paulo Coelho'})
MERGE (zusak:Author {name: 'Markus Zusak'})
MERGE (fitzgerald:Author {name: 'F. Scott Fitzgerald'})
MERGE (lee:Author {name: 'Harper Lee'})
MERGE (green:Author {name: 'John Green'})
MERGE (fantasy:Genre {name: 'Fantasy'})
MERGE (mystery:Genre {name: 'Mystery'})
MERGE (scienceFiction:Genre {name: 'Science Fiction'})
MERGE (romance:Genre {name: 'Romance'})
MERGE (adventure:Genre {name: 'Adventure'})
MERGE (historicalFiction:Genre {name: 'Historical Fiction'})
MERGE (dystopian:Genre {name: 'Dystopian'})
MERGE (classic:Genre {name: 'Classic'})
MERGE (youngAdult:Genre {name: 'Young Adult'})
MERGE (magic:Topic {name: 'Magic'})
MERGE (friendship:Topic {name: 'Friendship'})
MERGE (quest:Topic {name: 'Quest'})
MERGE (mythology:Topic {name: 'Mythology'})
MERGE (survival:Topic {name: 'Survival'})
MERGE (rebellion:Topic {name: 'Rebellion'})
MERGE (space:Topic {name: 'Space'})
MERGE (technology:Topic {name: 'Technology'})
MERGE (detective:Topic {name: 'Detective'})
MERGE (conspiracy:Topic {name: 'Conspiracy'})
MERGE (love:Topic {name: 'Love'})
MERGE (family:Topic {name: 'Family'})
MERGE (war:Topic {name: 'War'})
MERGE (society:Topic {name: 'Society'})
MERGE (comingOfAge:Topic {name: 'Coming of Age'})
MERGE (justice:Topic {name: 'Justice'})
MERGE (death:Topic {name: 'Death'})
MERGE (selfDiscovery:Topic {name: 'Self Discovery'})
MERGE (harry:Book {title: "Harry Potter and the Philosopher's Stone"})
SET harry.year = 1997
MERGE (harry)-[:WRITTEN_BY]->(jk)
MERGE (harry)-[:HAS_GENRE]->(fantasy)
MERGE (harry)-[:HAS_TOPIC]->(magic)
MERGE (harry)-[:HAS_TOPIC]->(friendship)
MERGE (hobbit:Book {title: 'The Hobbit'})
SET hobbit.year = 1937
MERGE (hobbit)-[:WRITTEN_BY]->(tolkien)
MERGE (hobbit)-[:HAS_GENRE]->(fantasy)
MERGE (hobbit)-[:HAS_GENRE]->(adventure)
MERGE (hobbit)-[:HAS_TOPIC]->(quest)
MERGE (hobbit)-[:HAS_TOPIC]->(friendship)
MERGE (lotr:Book {title: 'The Lord of the Rings'})
SET lotr.year = 1954
MERGE (lotr)-[:WRITTEN_BY]->(tolkien)
MERGE (lotr)-[:HAS_GENRE]->(fantasy)
MERGE (lotr)-[:HAS_GENRE]->(adventure)
MERGE (lotr)-[:HAS_TOPIC]->(quest)
MERGE (lotr)-[:HAS_TOPIC]->(rebellion)
MERGE (narnia:Book {title: 'The Chronicles of Narnia'})
SET narnia.year = 1950
MERGE (narnia)-[:WRITTEN_BY]->(lewis)
MERGE (narnia)-[:HAS_GENRE]->(fantasy)
MERGE (narnia)-[:HAS_GENRE]->(adventure)
MERGE (narnia)-[:HAS_TOPIC]->(magic)
MERGE (narnia)-[:HAS_TOPIC]->(quest)
MERGE (percy:Book {title: 'Percy Jackson and the Lightning Thief'})
SET percy.year = 2005
MERGE (percy)-[:WRITTEN_BY]->(riordan)
MERGE (percy)-[:HAS_GENRE]->(fantasy)
MERGE (percy)-[:HAS_GENRE]->(youngAdult)
MERGE (percy)-[:HAS_TOPIC]->(mythology)
MERGE (percy)-[:HAS_TOPIC]->(quest)
MERGE (hungerGames:Book {title: 'The Hunger Games'})
SET hungerGames.year = 2008
MERGE (hungerGames)-[:WRITTEN_BY]->(collins)
MERGE (hungerGames)-[:HAS_GENRE]->(dystopian)
MERGE (hungerGames)-[:HAS_GENRE]->(youngAdult)
MERGE (hungerGames)-[:HAS_TOPIC]->(survival)
MERGE (hungerGames)-[:HAS_TOPIC]->(rebellion)
MERGE (mazeRunner:Book {title: 'The Maze Runner'})
SET mazeRunner.year = 2009
MERGE (mazeRunner)-[:WRITTEN_BY]->(dashner)
MERGE (mazeRunner)-[:HAS_GENRE]->(dystopian)
MERGE (mazeRunner)-[:HAS_GENRE]->(youngAdult)
MERGE (mazeRunner)-[:HAS_TOPIC]->(survival)
MERGE (mazeRunner)-[:HAS_TOPIC]->(technology)
MERGE (dune:Book {title: 'Dune'})
SET dune.year = 1965
MERGE (dune)-[:WRITTEN_BY]->(herbert)
MERGE (dune)-[:HAS_GENRE]->(scienceFiction)
MERGE (dune)-[:HAS_GENRE]->(adventure)
MERGE (dune)-[:HAS_TOPIC]->(space)
MERGE (dune)-[:HAS_TOPIC]->(rebellion)
MERGE (nineteenEightyFour:Book {title: '1984'})
SET nineteenEightyFour.year = 1949
MERGE (nineteenEightyFour)-[:WRITTEN_BY]->(orwell)
MERGE (nineteenEightyFour)-[:HAS_GENRE]->(dystopian)
MERGE (nineteenEightyFour)-[:HAS_GENRE]->(scienceFiction)
MERGE (nineteenEightyFour)-[:HAS_TOPIC]->(society)
MERGE (nineteenEightyFour)-[:HAS_TOPIC]->(technology)
MERGE (martian:Book {title: 'The Martian'})
SET martian.year = 2011
MERGE (martian)-[:WRITTEN_BY]->(weir)
MERGE (martian)-[:HAS_GENRE]->(scienceFiction)
MERGE (martian)-[:HAS_GENRE]->(adventure)
MERGE (martian)-[:HAS_TOPIC]->(space)
MERGE (martian)-[:HAS_TOPIC]->(survival)
MERGE (sherlock:Book {title: 'Sherlock Holmes'})
SET sherlock.year = 1887
MERGE (sherlock)-[:WRITTEN_BY]->(doyle)
MERGE (sherlock)-[:HAS_GENRE]->(mystery)
MERGE (sherlock)-[:HAS_GENRE]->(classic)
MERGE (sherlock)-[:HAS_TOPIC]->(detective)
MERGE (sherlock)-[:HAS_TOPIC]->(justice)
MERGE (daVinci:Book {title: 'The Da Vinci Code'})
SET daVinci.year = 2003
MERGE (daVinci)-[:WRITTEN_BY]->(brown)
MERGE (daVinci)-[:HAS_GENRE]->(mystery)
MERGE (daVinci)-[:HAS_GENRE]->(adventure)
MERGE (daVinci)-[:HAS_TOPIC]->(conspiracy)
MERGE (daVinci)-[:HAS_TOPIC]->(detective)
MERGE (pride:Book {title: 'Pride and Prejudice'})
SET pride.year = 1813
MERGE (pride)-[:WRITTEN_BY]->(austen)
MERGE (pride)-[:HAS_GENRE]->(romance)
MERGE (pride)-[:HAS_GENRE]->(classic)
MERGE (pride)-[:HAS_TOPIC]->(love)
MERGE (pride)-[:HAS_TOPIC]->(society)
MERGE (janeEyre:Book {title: 'Jane Eyre'})
SET janeEyre.year = 1847
MERGE (janeEyre)-[:WRITTEN_BY]->(bronte)
MERGE (janeEyre)-[:HAS_GENRE]->(romance)
MERGE (janeEyre)-[:HAS_GENRE]->(classic)
MERGE (janeEyre)-[:HAS_TOPIC]->(love)
MERGE (janeEyre)-[:HAS_TOPIC]->(comingOfAge)
MERGE (littleWomen:Book {title: 'Little Women'})
SET littleWomen.year = 1868
MERGE (littleWomen)-[:WRITTEN_BY]->(alcott)
MERGE (littleWomen)-[:HAS_GENRE]->(historicalFiction)
MERGE (littleWomen)-[:HAS_GENRE]->(classic)
MERGE (littleWomen)-[:HAS_TOPIC]->(family)
MERGE (littleWomen)-[:HAS_TOPIC]->(comingOfAge)
MERGE (alchemist:Book {title: 'The Alchemist'})
SET alchemist.year = 1988
MERGE (alchemist)-[:WRITTEN_BY]->(coelho)
MERGE (alchemist)-[:HAS_GENRE]->(fantasy)
MERGE (alchemist)-[:HAS_GENRE]->(adventure)
MERGE (alchemist)-[:HAS_TOPIC]->(quest)
MERGE (alchemist)-[:HAS_TOPIC]->(selfDiscovery)
MERGE (bookThief:Book {title: 'The Book Thief'})
SET bookThief.year = 2005
MERGE (bookThief)-[:WRITTEN_BY]->(zusak)
MERGE (bookThief)-[:HAS_GENRE]->(historicalFiction)
MERGE (bookThief)-[:HAS_TOPIC]->(war)
MERGE (bookThief)-[:HAS_TOPIC]->(death)
MERGE (gatsby:Book {title: 'The Great Gatsby'})
SET gatsby.year = 1925
MERGE (gatsby)-[:WRITTEN_BY]->(fitzgerald)
MERGE (gatsby)-[:HAS_GENRE]->(classic)
MERGE (gatsby)-[:HAS_GENRE]->(romance)
MERGE (gatsby)-[:HAS_TOPIC]->(love)
MERGE (gatsby)-[:HAS_TOPIC]->(society)
MERGE (mockingbird:Book {title: 'To Kill a Mockingbird'})
SET mockingbird.year = 1960
MERGE (mockingbird)-[:WRITTEN_BY]->(lee)
MERGE (mockingbird)-[:HAS_GENRE]->(historicalFiction)
MERGE (mockingbird)-[:HAS_GENRE]->(classic)
MERGE (mockingbird)-[:HAS_TOPIC]->(justice)
MERGE (mockingbird)-[:HAS_TOPIC]->(comingOfAge)
MERGE (fault:Book {title: 'The Fault in Our Stars'})
SET fault.year = 2012
MERGE (fault)-[:WRITTEN_BY]->(green)
MERGE (fault)-[:HAS_GENRE]->(romance)
MERGE (fault)-[:HAS_GENRE]->(youngAdult)
MERGE (fault)-[:HAS_TOPIC]->(love)
MERGE (fault)-[:HAS_TOPIC]->(death)